# SPDX-FileCopyrightText: 2023 Eyad Issa <eyadlorenzo@gmail.com>
#
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: gomod
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
